/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppPagination: typeof import('./src/components/AppPagination.vue')['default']
    AppPaginatione: typeof import('./src/components/AppPaginatione.vue')['default']
    ErrorPage: typeof import('./src/components/ErrorPage.vue')['default']
    LoadingPage: typeof import('./src/components/LoadingPage.vue')['default']
    LodingPage: typeof import('./src/components/LodingPage.vue')['default']
    MovieList: typeof import('./src/components/MovieList.vue')['default']
    NotFound: typeof import('./src/components/NotFound.vue')['default']
    ReviewList: typeof import('./src/components/ReviewList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
